const allQuestionActionType = {
    CREATE_QUESTION_WITH_ANSWER: "CREATE_QUESTION_WITH_ANSWER",
    DELETE_QUESTION_LIST: "DELETE_QUESTION_LIST",
    DELETE_QUESTION_BY_ID: "DELETE_QUESTION_BY_ID",
    SORT_QUESTION_LIST: "SORT_ALL_QUESTION",
    EDIT_QUESTION_WITH_ANSWER: "EDIT_QUESTION_WITH_ANSWER",
    UPDATE_QUESTION_WITH_ANSWER: "UPDATE_QUESTION_WITH_ANSWER",
    CANCEL_QUESTION_EDIT: "CANCEL_QUESTION_EDIT",
};

export {allQuestionActionType};
